CREATE TABLE EMP AS
SELECT * FROM EMPLOYEES;

INSERT INTO EMP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (250, 'Erman', 'İbrisim', 'erman@ibrisim', '5556783245', TO_TIMESTAMP('03-10-2013 22:07:27', 'DD/MM/YYYY HH24:MI:SS'), 'IT_PROG', 10000, NULL, NULL, NULL);

ALTER SESSION SET nls_date_format = 'DD/MM/YYYY HH24:MI:SS';

SELECT *
FROM
    EMP e
WHERE e.employee_id=250;

UPDATE EMP e
SET e.phone_number = '5328976541', e.salary = 15000
WHERE e.employee_id = 250;

SELECT *
FROM
    EMP e
WHERE e.employee_id=250;

DELETE FROM EMP e
WHERE e.employee_id = 250;

SELECT * FROM EMP;

DROP TABLE EMP;